[workspace]
members = [
    "rcore-fs",
    "rcore-fs-sefs",
    "rcore-fs-cli",
    "rcore-fs-ramfs",
    "rcore-fs-mountfs",
    "rcore-fs-devfs",
    "rcore-fs-unionfs",
]
exclude = [
    "sefs-cli",
    "rcore-fs-sfs",
    "rcore-fs-ext2",
    "rcore-fs-hostfs",
]
